### ISSUE TITLE
UI Tasarımı

### ISSUE THREAD

**Issue by omersuatdemir** [omersuatdemir/todo-list#9]
uygulamanın genel ui tasarımı
notların listesi ve giriş ekranını içerecek. örnek:
![Image](https://github.com/omersuatdemir/todo-list/assets/108292163/c661ef27-6068-4df4-9361-64108eee8c82)

**Comment by zkrdg0** [comment]
![Image](https://github.com/omersuatdemir/todo-list/assets/161854574/fdd4f409-de61-4eb4-8548-aa2fd8d8b356)
